framework:
  rate_limiter:
    mfa:
      policy: "sliding_window"
      limit: 1
      interval: "60 seconds"
    password_reset:
      policy: "sliding_window"
      limit: 1
      interval: "60 seconds"
